# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa232e63981c2ae43dabbf46c8804a714d4e2ac742874a6a02c06fe10fe51f2bbd2652ad04ad9e11780e0825ccc85c2df9d2daeff41e4e9175bd26dd3cdbb4f1

test:
  secret_key_base: 4d96bd09630f00bf49b480f509bd644c98f40d373e202c67eeeae8a72b215d28250fb6e48d2cda8044a742c9ecc78691306c20b813f984064af2715b22fef7c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
